import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Droub Logistcis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>


        <link rel="icon" href="/logoWhite.svg" type='icon' sizes="any" />

      </head>
      <html lang="en">

        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
